# - id: doi:10.1371/journal.pcbi.1007128
  # type: paper
  # description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  # date: 2020-12-4
  # image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  # buttons:
    # - type: manubot
      # link: https://greenelab.github.io/meta-review/
    # - type: source
      # text: Manuscript Source
      # link: https://github.com/greenelab/meta-review
    # - type: website
      # link: http://manubot.org/
  # tags:
    # - open science
    # - collaboration
  # repo: greenelab/meta-review
# 
# - id: doi:10.1016/j.csbj.2020.05.017
  # image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg
# 
# - id: doi:10.7554/eLife.32822
  # image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp

- id: doi:10.1016/j.patter.2025.101240
  image: https://www.cell.com/cms/10.1016/j.patter.2025.101240/asset/311e9ed2-3189-4c76-a9eb-c30476eb1876/main.assets/gr1_lrg.jpg
# - id: DOI:10.1016/j.biopsych.2025.02.266

- id: DOI:10.1016/j.biopsych.2025.02.266
  # type: paper
  # description: Dissecting the exposome linked to mental health outcomes can help identify potentially modifiable targets to improve mental well-being. However, the multiplicity of exposures and the complexity of mental health phenotypes pose a challenge that requires data-driven approaches.
  # image: https://cdn.ncbi.nlm.nih.gov/pmc/blobs/d4d6/11968124/4268408163dd/S0033291724003015_fig3.jpg
  # buttons:
  #   - type: manubot
  #     link: test
  tags:
    - Behavioral Health

- id: doi:10.1101/2023.08.21.23294377
  image: https://www.medrxiv.org/content/medrxiv/early/2023/08/22/2023.08.21.23294377/F3.large.jpg?width=800&height=600&carousel=1

- id: doi:10.1101/2023.08.19.23294322
  image: https://www.medrxiv.org/content/medrxiv/early/2023/08/22/2023.08.19.23294322/F3.large.jpg?width=800&height=600&carousel=1

- id: doi:10.1162/netn_a_00063
  image: https://mitp.silverchair-cdn.com/mitp/content_public/journal/netn/3/1/10.1162_netn_a_00063/3/m_00063f03c.png?Expires=1777896020&Signature=R4r1Wims8j~yifrjPvVlMkEQ2kuji2cWAa7zB7XypLGsjBoqbSzenZJRKty2ln7hxxpVkOhgSk5O2CC55b9t-IeC78R-DyZNixsqgd4clwMp4wMzGUSIMQR7a8tIfP0QyLXR-VY75qRXDUEBRM-mOwe4sWZzXjpFUkme3LhkZxoYCnrO4rKZ~xlvc5Akz7vVf884eAmRdYo12ABY-~4pzSnyuIdyiLJyZWBgOmCgucNsaR4iA0aQcjUmivsUg4Rq2Iy7gg9E-5yWOk3SmUiQBWOJTyzIAgixXDTCDh3N09ph3Cu-XR6b-MWuHtSqR2lhLmvtOXFizYqj062DL1~ujw__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA 
   # - id: doi:10.1016/j.chc.2013.07.001 
- id: doi:10.64898/2026.02.23.26346921
  image: https://www.researchgate.net/publication/401240647/figure/fig1/AS:11431281967672868@1772094152267/Decision-curve-analysis-for-point-prediction-models-Standardized-net-benefit-sNB-is.png

- id: doi:10.3389/fpsyt.2025.1487894
  image: https://images-provider.frontiersin.org/api/ipx/w=716&f=webp/https://www.frontiersin.org/files/Articles/1487894/xml-images/fpsyt-16-1487894-g003.webp
# - id: doi:10.1016/j.biopsych.2025.02.266
- id: doi:10.1016/j.patter.2025.101240
- id: doi:10.1038/s41398-023-02599-9
  image: https://cdn.ncbi.nlm.nih.gov/pmc/blobs/af65/10564881/511a77d4ea4f/41398_2023_2599_Fig2_HTML.jpg

- id: doi:10.3389/fpsyt.2023.1280326
  image: https://images-provider.frontiersin.org/api/ipx/w=716&f=webp/https://www.frontiersin.org/files/Articles/1280326/xml-images/fpsyt-14-1280326-g0002.webp

- id: doi:10.1101/2023.10.23.23297438
  image: https://www.medrxiv.org/content/medrxiv/early/2023/10/24/2023.10.23.23297438/F3.large.jpg?width=800&height=600&carousel=1

- id: doi:10.3389/frai.2022.832530
  image: https://images-provider.frontiersin.org/api/ipx/w=716&f=webp/https://www.frontiersin.org/files/Articles/832530/xml-images/frai-05-832530-g0003.webp

- id: doi:10.1080/17588928.2020.1793752
- id: doi:10.1016/j.neuroimage.2019.116116
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1053811919307074-gr1.jpg

- id: doi:10.3389/fnins.2019.00332
  image: https://images-provider.frontiersin.org/api/ipx/w=716&f=webp/https://www.frontiersin.org/files/Articles/414031/xml-images/fnins-13-00332-g001.webp

- id: doi:10.1089/neu.2018.5629
- id: doi:10.1162/netn_a_00063
- id: doi:10.1002/hbm.24187
  image: https://cdn.ncbi.nlm.nih.gov/pmc/blobs/9119/6866542/9ec7fc467429/HBM-39-3449-g004.jpg

- id: doi:10.1016/j.neuroimage.2018.06.003
  image: https://ars.els-cdn.com/content/image/1-s2.0-S105381191830510X-gr3.jpg

- id: doi:10.1097/DBP.0000000000000613
- id: doi:10.1097/HTR.0000000000000381
- id: doi:10.1016/j.nicl.2017.05.024
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2213158217301298-gr1.jpg

- id: doi:10.1136/jmedgenet-2015-103087
  image: https://jmg.bmj.com/content/jmedgenet/52/8/514/F3.medium.gif

- id: doi:10.1016/j.chc.2013.07.001

- id: doi:10.1038/s41746-026-02580-y
