# - id: doi:10.1371/journal.pcbi.1007128
  # type: paper
  # description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  # date: 2020-12-4
  # image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  # buttons:
    # - type: manubot
      # link: https://greenelab.github.io/meta-review/
    # - type: source
      # text: Manuscript Source
      # link: https://github.com/greenelab/meta-review
    # - type: website
      # link: http://manubot.org/
  # tags:
    # - open science
    # - collaboration
  # repo: greenelab/meta-review
# 
# - id: doi:10.1016/j.csbj.2020.05.017
  # image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg
# 
# - id: doi:10.7554/eLife.32822
  # image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp

- id: doi:10.1016/j.patter.2025.101240
  image: https://www.cell.com/cms/10.1016/j.patter.2025.101240/asset/311e9ed2-3189-4c76-a9eb-c30476eb1876/main.assets/gr1_lrg.jpg
# - id: DOI:10.1016/j.biopsych.2025.02.266

- id: DOI:10.1016/j.biopsych.2025.02.266
  type: paper
  description: Dissecting the exposome linked to mental health outcomes can help identify potentially modifiable targets to improve mental well-being. However, the multiplicity of exposures and the complexity of mental health phenotypes pose a challenge that requires data-driven approaches.
  # image: https://cdn.ncbi.nlm.nih.gov/pmc/blobs/d4d6/11968124/4268408163dd/S0033291724003015_fig3.jpg
  # buttons:
  #   - type: manubot
  #     link: test
  tags:
    - Behavioral Health

- id: doi:10.1101/2023.08.21.23294377
  image: https://www.medrxiv.org/content/medrxiv/early/2023/08/22/2023.08.21.23294377/F3.large.jpg?width=800&height=600&carousel=1

- id: doi:10.1101/2023.08.19.23294322
  image: https://www.medrxiv.org/content/medrxiv/early/2023/08/22/2023.08.19.23294322/F3.large.jpg?width=800&height=600&carousel=1

- id: doi:10.1162/netn_a_00063
  image: https://mitp.silverchair-cdn.com/mitp/content_public/journal/netn/3/1/10.1162_netn_a_00063/3/00063f01c.png?Expires=1774840272&Signature=my3H9ADbJQHnVq36dVHaqIWsDYHjmmF7-00~bn8NQz3dkApyizp-d29W16BD3-sBjcYdYhGZDBvjFbuURtv1soeoIzOHd0t1ZPWIYpUC9-YlRBn5dkqvsoCcQU-RMd5GmaiPK5cuMOpoHT~g-P6pbmEHBXVOsk13k1RCxVKVT3f9FZERfleuAqj3iy7sOfO5whOuc4k8-m7eSpZWiiK9KsbkYamcsuL2~pOhQFyEvABv0kIM6zt46fa9pHLwif95V8Db7HA5gVde3Twt3k9KpScSsPP9rXiHhzzCCnQasUBj~HU6WdOO9sxIgEVkei4sKNBclWVE-OwW36klGwsFMA__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

# - id: doi:10.1016/j.chc.2013.07.001 

- id: doi:10.3389/fpsyt.2025.1487894
# - id: doi:10.1016/j.biopsych.2025.02.266
- id: doi:10.1016/j.patter.2025.101240
- id: doi:10.1038/s41398-023-02599-9
- id: doi:10.3389/fpsyt.2023.1280326
- id: doi:10.1101/2023.10.23.23297438
- id: doi:10.3389/frai.2022.832530
- id: doi:10.1080/17588928.2020.1793752
- id: doi:10.1016/j.neuroimage.2019.116116
- id: doi:10.3389/fnins.2019.00332
- id: doi:10.1089/neu.2018.5629
- id: doi:10.1162/netn_a_00063
- id: doi:10.1002/hbm.24187
- id: doi:10.1016/j.neuroimage.2018.06.003
- id: doi:10.1097/DBP.0000000000000613
- id: doi:10.1097/HTR.0000000000000381
- id: doi:10.1016/j.nicl.2017.05.024
- id: doi:10.1136/jmedgenet-2015-103087
- id: doi:10.1016/j.chc.2013.07.001